#!/bin/bash
set -e

# 使用 psql 執行指令，這裡可以直接讀取環境變數 $API_USER_PASSWORD
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER api_user WITH PASSWORD '$API_USER_PASSWORD';
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO api_user;
    GRANT USAGE ON SCHEMA public TO api_user;
    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO api_user;
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO api_user;
EOSQL