"""empty message

Revision ID: f7d669704785
Revises: 
Create Date: 2026-01-30 08:15:41.394099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d669704785'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('article_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_board', sa.String(length=50), nullable=False),
    sa.Column('article_title', sa.String(length=50), nullable=False),
    sa.Column('article_content', sa.Text(), nullable=False),
    sa.Column('article_upload_time', sa.DateTime(), nullable=False),
    sa.Column('writer_id', sa.String(length=80), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_table('boards',
    sa.Column('board_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('board_eng', sa.String(length=50), nullable=False),
    sa.Column('board_zh', sa.String(length=50), nullable=False),
    sa.Column('board_n_articles', sa.Integer(), nullable=False),
    sa.Column('board_last_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('board_id', 'board_eng'),
    sa.UniqueConstraint('board_eng'),
    sa.UniqueConstraint('board_id')
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('comment_content', sa.Text(), nullable=False),
    sa.Column('comment_upload_time', sa.DateTime(), nullable=False),
    sa.Column('writer_id', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('is_manager', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('comments')
    op.drop_table('boards')
    op.drop_table('articles')
    # ### end Alembic commands ###
